### ISSUE TITLE
README.md  ‘Phone SDK Integration Guide’  404

### ISSUE THREAD

**Issue by RedTomatoCat** [google/android-auto-companion-android#1]
https://docs.partner.android.com/gas/integrate/companion_app/cd_phone_sdk
 
open code 404

**Comment by LouisCAD** [comment]
@yaoyx108?

**Comment by yaoyx108** [comment]
Currently the link is only accessible with an Android partner account. Otherwise the website will return 404.

Please work with your program manager to gain access. 

I've added a note to the README.
