### ISSUE TITLE
help-wanted: Android Auto: why is the publication in Google Play rejected

### ISSUE THREAD

**Issue by AlejandroGomz** [google/android-auto-companion-android#2]
Hi,

I'm working on android auto. The app runs on DHU but publishing in Google Play was rejected:

Reason: application asks for an update which prevents testing of functionality in the Android Auto environment.

Don't know what's the reason is. Does anyone know what's to do?

the link for the instructions of your sdk is unfortunately dead.
posted this question also in [stackoverflow](https://stackoverflow.com/questions/74159149/android-auto-why-is-the-publication-in-google-play-rejected) and got the hint to ask here at your place.

Thanks, Alejandro

**Comment by yaoyx108** [comment]
Hi, this repo hosts the SDK for building a companion app for an infotainment unit that runs Android Automotive OS. 

The repo is not related to Android Auto. I will close this issue.
